### ISSUE TITLE
NumberBox

### ISSUE THREAD

**Issue by IOExcept10n** [System-IOException/WASP-Homework#10]
@GalteXx , Вроде сделал класс, но у меня возник один достаточно странный баг.
Когда я создаю данный объект, у меня он отрисовывается вот так:
![изображение](https://user-images.githubusercontent.com/56886020/147351214-2587f59e-101a-4330-b76a-48499bddab02.png)
Явно видно, что кнопка справа (у меня она уменьшает) квадратная, а кнопка слева в 2 раза меньше.
Поле для текста тогда должно быть больше на одну восьмую, но это сложновато отследить. Но это не имеет особого значения. Когда я проверяю размеры элементов через отладку, мне показывает вот это:
![изображение](https://user-images.githubusercontent.com/56886020/147351401-7907f565-3f6f-4933-b0a3-864b59c73e3e.png)
![изображение](https://user-images.githubusercontent.com/56886020/147351413-02db1353-ac9a-44d7-afe2-f1fbf62d1847.png)
![изображение](https://user-images.githubusercontent.com/56886020/147351424-9a0ee963-dd0f-4619-8274-c0c5d16e90b6.png)
И тут ширина кнопок одинаковая! Как это работает и почему они на картинке имеют другой размер?

**Comment by GalteXx** [comment]
Лучше спрашивай в тг, так быстрее отвечаю. Скорее всего у тебя одна кнопка уехала под другую

**Comment by IOExcept10n** [comment]
Всё, исправил
![изображение](https://user-images.githubusercontent.com/56886020/147559194-321526bb-8586-4f82-a6f3-04ad96d3d3b6.png)
