### ISSUE TITLE
Unity homework 1

### ISSUE THREAD

**Issue by IOExcept10n** [System-IOException/WASP-Homework#12]
@shadowAnonim

**Comment by shadowAnonim** [comment]
Время между яблоками 120 секунд по умолчанию - это странно, но так как это не прописано в тз, то ок.
На будущее, вызывать GameObject.Find в Update не очень хорошо влияет на оптимизацию. Лучше, например, сделать скрипт, привязанный к корзине, который её двигает или хранить список корзин в основном скрипте и в Update к нему обращаться.

Оценка:
Сделано хорошо, но из-за одной ошибки не исчезают яблоки при попадании в корзину. -1
Итого 3/4, если исправишь уничтожение яблок, поставлю 4.

**Comment by IOExcept10n** [comment]
Ну насчёт времени в 120 секунд не знаю, у меня вроде нормально работает, да и в скрипте оно как 1f выставлено ¯\_(ツ)_/¯
А насчёт яблок, надо все уничтожать после попадания хотя бы одного в корзину?
Просто я такого бага не заметил. Я немного изменил и перезалил код, теперь он удаляет все яблоки при прикосновении к корзине

**Comment by shadowAnonim** [comment]
Вот сейчас всё хорошо с временем и с уничтожением. 4/4
