### ISSUE TITLE
Автопарк

### ISSUE THREAD

**Issue by IOExcept10n** [System-IOException/WASP-Homework#3]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Шустрый. Самоучка?)

**Comment by vdetstvepil** [comment]
Принято.

**Comment by IOExcept10n** [comment]
В 7 классе учился, но курс быстро закрыли, мало успел пройти. Поэтому сейчас решил углубиться в изучение)
Ну и плюс хочется технологиями различным овладеть

**Comment by vdetstvepil** [comment]
Понял, принял) прикольно. Отличный код!
