### ISSUE TITLE
Метрополитен 3

### ISSUE THREAD

**Issue by IOExcept10n** [System-IOException/WASP-Homework#4]
@vdetstvepil , последнее (?) задание по метрополитену решено. Очень классная идея для решения через предыдущую и следующую станции, с помощью неё удобно решать. Правда, пока я не ввёл лимит на длину маршрута, она решала бесконечно долго, без этого лимита она вроде вообще в какую-то бесконечную рекурсию уходит, не знаете случайно, как это можно решить?

**Comment by vdetstvepil** [comment]
Вау. Очень и очень неплохо. 🎉

- Вывод всех станций на экран. Было бы неплохо как-то упорядочить ветки, а то у тебя вразнобой выводятся станции, получается путаница. А еще местами выплывает шедевр в виде веток "3" и " 3". Это ж одна и та же ветка :) Но в программе это почему-то разные ветки. Всё остальное выглядит достаточно солидно.
- При выводе станции определенной ветки программа сломалась:
![image](https://user-images.githubusercontent.com/53276813/141179716-7ecda733-18af-4d1f-8194-741a0f538de4.png)
![image](https://user-images.githubusercontent.com/53276813/141179732-0955dcb7-f5d5-47db-9d47-1c0c4f126585.png)
- При выводе станций по названию программа ушла в бесконечный цикл:
![image](https://user-images.githubusercontent.com/53276813/141180004-7f2e11fb-4ac8-46fc-b4ff-a6e0e9cf166a.png)
![image](https://user-images.githubusercontent.com/53276813/141180079-a950674f-3576-4723-be4c-6eaf40f51e4e.png)
- Маршрут тоже чет не строится, хотя я корректные данные ввожу...
![image](https://user-images.githubusercontent.com/53276813/141180300-f64df79c-b5c7-42e7-9877-291d35544037.png)

**Comment by vdetstvepil** [comment]
А ты отмечаешь посещенные станции метро? Если нет, то программа легко может уйти в бесконечную рекурсию. Как костыль можно использовать лимит на маршрут, соответственно, 50 вхождений. Если рекурсия уйдет дальше, обрывать процедуру со словами "извините".

**Comment by vdetstvepil** [comment]
Можем посмотреть проект вместе после четверга и подумать, как да что поправить. Тыкай меня с вопросами в телеге, если будут

**Comment by vdetstvepil** [comment]
Принято.
